version: '3.3'

services:
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./src/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  chromadb:
    image: chromadb/chroma:latest
    restart: always
    environment:
      - ALLOW_RESET=TRUE
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE}
    volumes:
      - ./chromadb:/chroma/chroma
    ports:
      - 8000:8000